### ISSUE TITLE
js events

### ISSUE THREAD

**Issue by max-schu** [BKWLD/vue-in-viewport-directive#1]
thanks for the directive, it works as expected!
However, i think it would be great to also fire some events to make it accessible not only through css.
What do you think about that, any ideas / plans?

cheers!

**Comment by weotch** [comment]
Huh, interesting.  I guess, as a directive, it would be possible to fire arbitrary JS events (like as opposed to Vue events).  

However, when I've needed to do more complicated things, I use this other, related, package we made: https://github.com/BKWLD/vue-in-viewport-mixin.  Have you seen it?  It might work for your needs.

**Comment by max-schu** [comment]
mhm the mixin works for components only, so unless you wrap every single el in a comp it's not gonna do the job right?

Gonna go with standalone scrollMonitor, thank you for building the mixin and directive though!

**Comment by weotch** [comment]
Yeah, that is true.

Sure, you bet!
