### ISSUE TITLE
not working wit CSS Scroll Snapping

### ISSUE THREAD

**Issue by clexi** [BKWLD/vue-in-viewport-directive#9]
i'm using css scroll snap like: https://css-tricks.com/practical-css-scroll-snapping/
In this case `v-in-viewport` not working anymore. 
Do you have any idea to fix this? Or another way to realize this snappy scroll? Maybe another vue component? 
Thanks!

**Comment by weotch** [comment]
I've not used that property before, looks cool though! I wanna try it out asap. 

Anyway, what version of this directive are you using. I recently did a breaking change to use IntersectionObserver.

**Comment by clexi** [comment]
I'm using: `"vue-in-viewport-directive": "^1.3.0",`

**Comment by weotch** [comment]
See if the 2.0 version fixes it for you

**Comment by clexi** [comment]
Okay i will test it, but actually this version is not available for yarn/npm :(

**Comment by weotch** [comment]
![](https://i.imgur.com/zivxHE1.gif)

😅 Try it now

**Comment by clexi** [comment]
Great Thanks!
